version: "1.2.0"
services:
  myhousevpn-ui:
    image: myhousevpn/uimyhousevpn:latest
    container_name: myhousevpn-ui
    ports:
      - "51821:51821" # Maps port 51821 on the host to port 51821 in the container
    restart: unless-stopped
    environment:
      DEBUG: "Server,SSH"
